apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-search.my-apps.tap.20240116141252.0.0+build.02e9424
spec:
  refName: where-for-dinner-search.my-apps.tap
  version: 20240116141252.0.0+build.02e9424
  releaseNotes: |
    Release v20240116141252.0.0+build.02e9424 of package where-for-dinner-search.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-14-01-2024-06-46-52-642319129/where-for-dinner-search-my-apps-bundle@sha256:c7b69a9cf88ba73c18a97c9aec0807dce709884737aa65a7725a60022d0629c0
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

