apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner-ui.my-apps.tap.20240114072037.0.0+build.02e9424
spec:
  refName: where-for-dinner-ui.my-apps.tap
  version: 20240114072037.0.0+build.02e9424
  releaseNotes: |
    Release v20240114072037.0.0+build.02e9424 of package where-for-dinner-ui.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-14-01-2024-06-46-52-642319129/where-for-dinner-ui-my-apps-bundle@sha256:e92c47c419b3c5c1d1718fb4e9629dc34d62e6ffa0641c13ccb9a7c0c688fbcd
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

