apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: where-for-dinner.my-apps.tap.20240114071942.0.0+build.02e9424
spec:
  refName: where-for-dinner.my-apps.tap
  version: 20240114071942.0.0+build.02e9424
  releaseNotes: |
    Release v20240114071942.0.0+build.02e9424 of package where-for-dinner.my-apps.tap
  template:
    spec:
      fetch:
      - imgpkgBundle:
          image: dev.registry.tanzu.vmware.com/tanzu-application-platform/ci-pipeline/apps-14-01-2024-06-46-52-642319129/where-for-dinner-my-apps-bundle@sha256:7dc89b073cea35ce76a23824fdc822ad84f5936f3518ea3c8886446c5bf1877d
      template:
      - ytt:
          paths:
          - .
      - kbld:
          paths:
          - .imgpkg/images.yml
          - '-'
      deploy:
      - kapp: {}
  valuesSchema:
    openAPIv3:
      type: object
      additionalProperties: false
      properties:
        workload_name:
          type: string
          default: ""

